// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2ZrmgfgPSU6pbICQ9j7arIGVr8jxawQA',
    appId: '1:346378259556:web:54f3d05ff6645ea3be2371',
    messagingSenderId: '346378259556',
    projectId: 'mogrym-c5981',
    authDomain: 'mogrym-c5981.firebaseapp.com',
    databaseURL: 'https://mogrym-c5981.firebaseio.com',
    storageBucket: 'mogrym-c5981.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcB1XyoGkBgW84QK2H4izlPiyxRHaMTAg',
    appId: '1:346378259556:android:9d18559724711939be2371',
    messagingSenderId: '346378259556',
    projectId: 'mogrym-c5981',
    databaseURL: 'https://mogrym-c5981.firebaseio.com',
    storageBucket: 'mogrym-c5981.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOubWjhi7xai5ZXKEXbS-5xDaxVdmIrQQ',
    appId: '1:346378259556:ios:459aa8f50174e244be2371',
    messagingSenderId: '346378259556',
    projectId: 'mogrym-c5981',
    databaseURL: 'https://mogrym-c5981.firebaseio.com',
    storageBucket: 'mogrym-c5981.appspot.com',
    iosClientId: '346378259556-lkucinp9dn9afjeeeeh2rrpac45rmhm7.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelerApp',
  );
}
